name: betrayer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.28.0
  cupertino_icons: ^1.0.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/bg/bg.jpg
    - assets/images/flies/015-dead.png
    - assets/images/flies/016-angry.png
    - assets/images/flies/037-angry.png
    - assets/images/flies/050-angry.png
    - assets/images/flies/046-crazy.png
    - assets/images/flies/028-poker-face.png
    - assets/images/flies/fly_1.png
    - assets/images/flies/fly_2.png
    - assets/images/flies/fly_3.png
    - assets/images/flies/fly_4.png
    - assets/images/flies/fly_5.png
    - assets/images/flies/fly_6.png
    - assets/images/flies/fly_7.png
    - assets/images/flies/fly_8.png
    - assets/images/flies/fly_9.png
    - assets/images/flies/fly_10.png
    - assets/images/flies/fly_11.png
    - assets/images/flies/fly_12.png
    - assets/images/flies/fly_13.png
    - assets/images/flies/fly_14.png
    - assets/images/flies/fly_15.png
    - assets/images/flies/fly_16.png
    - assets/images/flies/fly_17.png
    - assets/images/flies/fly_18.png
    - assets/images/flies/fly_19.png
    - assets/images/flies/fly_20.png
    - assets/images/menu/f.jpg
    - assets/images/menu/goal.jpg
    - assets/images/menu/handshake.png
    - assets/images/menu/henlo-human.jpg
    - assets/images/menu/imade.jpg
    - assets/images/menu/information.png
    - assets/images/menu/start.png
    - assets/images/menu/speech-bubble.png
    - assets/audio/sfx/ouch_1.mp3
    - assets/audio/sfx/ouch_2.mp3
    - assets/audio/sfx/ha_ha_1.mp3
    - assets/audio/sfx/ha_ha_2.mp3








